/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function initialized(): string
export interface TigaReadResult {
  lastId: number
  entries: Array<TigaEntry>
}
export interface TigaEntry {
  id: number
  message: Buffer
  mediaType?: string
}
export declare function tigaWrite(name: string, message: Buffer | string, mediaType?: string | null): string
export declare function tigaRead(name: string, lastId?: number): TigaReadResult
export declare function tigaInvoke(requestName: string, responseName: string, method: string, data: string, timeoutMs?: number): string
