/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function initialized(): string
export interface TigaReadResult {
  lastId: number
  entries: Array<TigaEntry>
}
export interface TigaEntry {
  id: number
  message: Buffer
  mediaType?: string
}
export interface TigaChannelOptions {
  mappingDirectory?: string
}
export interface TigaWriteOptions extends TigaChannelOptions {
  mediaType?: string | null
}
export interface TigaReadOptions extends TigaChannelOptions {
  lastId?: number
}
export interface TigaInvokeOptions extends TigaChannelOptions {
  timeoutMs?: number
}
export declare function tigaWrite(name: string, message: Buffer | string, options?: TigaWriteOptions): string
export declare function tigaRead(name: string, options?: TigaReadOptions): TigaReadResult
export declare function tigaInvoke(requestName: string, responseName: string, method: string, data: string, options?: TigaInvokeOptions): string
